# .github/workflows/build_and_publish.yml

name: Build and Publish to NPM
on:
  push:
    branches:
      - main

# by default, permissions are read-only, read + write is required for git pushes
permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ASDF Parse
        uses: kota65535/github-asdf-parse-action@v1.1.0
        id: versions

      - uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.versions.outputs.nodejs }}"
          registry-url: 'https://registry.npmjs.org'

      - name: Make sure it runs
        timeout-minutes: 1
        run: |
          # turn off error reporting to test the resulting exit code
          set +e

          # TODO would be better to do a output test, but I've already wasted enough time on node
          node --expose-internals -r internal/test/binding bin/run.js

          if [ $? -eq 9 ]; then
              # this is the expected exit code
              :
          else
            echo "inspector did not exit properly"
            exit 1
          fi

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          version-file: "./package.json,./package-lock.json"
          output-file: "CHANGELOG.md"

      - name: Publish to NPM
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: npm publish
        env:
          # `gh secret set NPM_TOKEN --app actions --body $NPM_TOKEN`
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Github Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: softprops/action-gh-release@v1
        with:
          # output options: https://github.com/TriPSs/conventional-changelog-action#outputs
          body: ${{ steps.changelog.outputs.clean_changelog }}
          tag_name: ${{ steps.changelog.outputs.tag }}

      - name: Sync Repository Metata
        # uses: kbrashears5/github-action-repo-sync@v1.0.0
        uses: iloveitaly/github-action-repo-sync@python
        with:
          TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
