# .github/workflows/build_and_publish.yml

name: Build and Publish to NPM
on:
  push:
    branches:
      - main

# by default, permissions are read-only, read + write is required for git pushes
permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ASDF Parse
        uses: kota65535/github-asdf-parse-action@v1.1.0
        id: versions

      - uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.versions.outputs.nodejs }}"

      - name: Make sure it runs
        timeout-minutes: 1
        run: |
          # TODO would be better to do a output test
          # npx better-node-inspect --port=0 -e "console.log('Hello World')" <<< '.exit'
          # npx better-node-inspect
          # node --expose-internals -r internal/test/binding --debug-port=0 bin/run.js
          sh bin/run.js

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          version-file: "./package.json,./package-lock.json"
          output-file: "CHANGELOG.md"

      - name: Publish to NPM
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: npm publish
        env:
          # `gh secret set NPM_TOKEN --app actions --body $PYPI_API_TOKEN`
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Github Release
      #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     # output options: https://github.com/TriPSs/conventional-changelog-action#outputs
      #     body: ${{ steps.changelog.outputs.clean_changelog }}
      #     tag_name: ${{ steps.changelog.outputs.tag }}
